# Uncomment the next line to define a global platform for your project
# platform :ios, '14.7'

target 'MYLOG_iOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MYLOG_iOS
	pod 'Alamofire'
	pod 'Moya'
	pod 'Moya/RxSwift'
	pod 'RxSwift'
	pod 'RxCocoa'
	pod 'SnapKit'
	pod 'Then'
	pod 'FSCalendar'
	pod 'Kingfisher'

end
