# Uncomment the next line to define a global platform for your project
# platform :ios, '15.0'

target 'MYLOG_iOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MYLOG_iOS
	pod 'Alamofire'
	pod 'Moya'
	pod 'Moya/RxSwift'
	pod 'RxSwift'
	pod 'RxCocoa'
	pod 'SnapKit'
	pod 'Then'
	pod 'Kingfisher'
	pod 'FSCalendar'
	pod 'FloatingPanel'

end


post_install do |installer|
    installer.generated_projects.each do |project|
          project.targets.each do |target|
              target.build_configurations.each do |config|
                  config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'
               end
          end
   end
end
